package com.example.demo_sb_customer.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import com.example.demo_sb_customer.entity.CustomerEntity;

@Repository // bean
public interface CustomerRepository extends JpaRepository<CustomerEntity, Long> {
  // ! During maven compilation, the implementation class is generated by Hibernate
  // save()
  // saveAll()
  // findAll()
  // findById()
  // deleteById()
  
}